### ISSUE TITLE
bloodborne crash after character creation 

### ISSUE THREAD

**Issue by GerinCtta** [shadps4-emu/shadPS4#888] opened 2024-09-12 17:33 UTC
[shad_log.txt](https://github.com/user-attachments/files/16983405/shad_log.txt)

my pc config r7 5700x rx7600 8gb 16gbram dd4 3200mhz

**Comment by Ghogost** [comment] 2024-09-12 17:39
maybe is for radeons, cuz mine crashes too and its a rx7600

**Comment by corigne** [comment] 2024-09-12 18:49
I have a similar crash with a NVIDIA card, so I don't think it is isolated to Radeon graphics.

Which client are you using? (I'm on linux)

**Comment by Ghogost** [comment] 2024-09-12 18:50
im using windows

**Comment by h16033** [comment] 2024-09-12 22:58
> I have a similar crash with a NVIDIA card, so I don't think it is isolated to Radeon graphics.
> 
> Which client are you using? (I'm on linux)

which distro you have

**Comment by corigne** [comment] 2024-09-12 23:38
> > I have a similar crash with a NVIDIA card, so I don't think it is isolated to Radeon graphics.
> > Which client are you using? (I'm on linux)
> 
> which distro you have

Arch rolling x86-64, Linux 6.10.9-arch1-1. 
Nvidia 2070 SUPER
Ryzen 7 3800X
32GB of RAM

I've made a couple of specific issues for the problems I've been running into on main. I was able to get it running to character creation on a fork that's fairly close to the main branch, but it crashes after character creation.

#885 
#886

**Comment by Purenuggetry** [comment] 2024-09-13 01:58
Mine also (Nvidia).. luckily game saves at crash and restarting picks up after character creation.

**Comment by corigne** [comment] 2024-09-13 01:59
> Mine also (Nvidia).. luckily game saves at crash and restarting picks up after character creation.

I had to leave home when I got the crash, or else I might have tried this. I will see if this works for me too!

**Comment by Ninomaker** [comment] 2024-09-13 06:01
facing the same issue too

**Comment by StevenMiller123** [comment] 2024-09-13 17:33
The `Failed allocating buffer with error ErrorOutOfDeviceMemory` error occurs when your graphics card runs out of VRAM. Make sure your graphics drivers are completely up to date, and that you aren't applying any user-made patches when testing.

**Comment by lolleri200** [comment] 2024-09-23 21:48
I am also facing this issue. I got Nvidia RTX 3070

**Comment by Hermiten** [comment] 2024-10-01 22:04
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/498

**Closed as completed by Hermiten** 2024-10-01 22:04 UTC
