### ISSUE TITLE
control settings

### ISSUE THREAD

**Issue by jotabluu** [shadps4-emu/shadPS4#864] opened 2024-09-10 21:19 UTC
i cant play the emulator cus it need me to have a numeric pad, is there a way to change the controls? i dont have a joystick either

**Comment by p4rallax** [comment] 2024-09-17 00:22
same. I saw there was a commit last week that added a GUI to change keyboard mapping , but I don't see any such option in the emulator. Clicking on the controller icon in the toolbar does nothing for me

**Comment by Rheckar** [comment] 2024-09-21 20:54
I was also wondering why the controller icon wasn't working after seeing that gui commit, is it for when you're using a gamepad or is it not yet supported to configure controls?

**Comment by p4rallax** [comment] 2024-09-22 00:54
@Rheckar  I just found out that the PR was reverted due to some errors. Will probably get implemented sooner or later.

**Comment by HeinrichVonStinkenfinger** [comment] 2024-09-22 01:50
> i cant play the emulator cus it need me to have a numeric pad, is there a way to change the controls? i dont have a joystick either

Yes as I myself have this issue. Make your resolution 720p, drag the game's screen to the middle top of the screen, then hit Ctrl + Windows Symbol + O to open virtual keyboard and then press numlock. Now you can use the numpad!

**Comment by Rheckar** [comment] 2024-09-22 08:39
Using the keyboard manager of the power toys app you can rebind keys of the keyboard to respond with other keys, until the problems are fixed this seems to work well. Its easy to switch on and off as well. Only problem is it doesn't let you assign keys to mouse buttons which would have been perfect...

**Comment by nghi01** [comment] 2024-09-30 19:53
Any updates on the current build for control settings? I read somewhere that the control mapping GUI was reverted due to an error in build.

**Comment by Hermiten** [comment] 2024-10-01 20:46
Duplicate of this one: https://github.com/shadps4-emu/shadPS4/issues/298

It was merged but reverted. The icon is still here on the GUI but not usable for now. They plan to do it again but maybe on a different way

**Comment by polybiusproxy** [comment] 2024-10-04 07:35
Closing as duplicate

**Closed as not planned by polybiusproxy** 2024-10-04 07:35 UTC
Labels: enhancement
