### ISSUE TITLE
Rich Presence doesnt show game activity on v0.4.0

### ISSUE THREAD

**Issue by Cyclizar** [shadps4-emu/shadPS4#1479] opened 2024-11-03 22:19 UTC
It was working fine on v0.3.1, then it stopped working on v0.3.1, and it isn't working on v0.4.0. It always says "Idle" instead of ingame or whatever.

![Screenshot 2024-11-01 143527](https://github.com/user-attachments/assets/c58dd39f-8621-4af0-bf0a-49fa60f40798)

**Comment by Hermiten** [comment] 2024-11-10 21:14
Do you know exactly when it stop to work ? Which commit ? And maybe provide more information like OS, GPU, etc...

**Comment by Hermiten** [comment] 2024-12-01 14:21
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/1317

**Closed as completed by Hermiten** 2024-12-01 14:21 UTC
