### ISSUE TITLE
[Bloodborne] 3 bugs right after character creation

### ISSUE THREAD

**Issue by ovojake** [shadps4-emu/shadPS4#1562] opened 2024-11-21 10:51 UTC
This is my first time playing this emulator, let me know if you need more details. I'm on the latest shadps4 update, no mods other than the sound pack (wasn't getting certain audio without it).

Problems in order:
1. epileptic white flickering in the Clinic, right after the very first cutscene. seems to come from the door windows
2. vertex explosion after the first cutscene in the Hunters Dream, fixed by unequipping clothing and reloading the save
3. crash to desktop whenever I try equipping the Hunters Garb. My whole PC freezes up for about 30 seconds then the game, emulator and console window all crash, so I don't have a chance to read the error.

**Comment by GHU7924** [comment] 2024-11-21 11:15
Specify the characteristics of your computer: CPU, GPU, amount of RAM, operating system.
Specify the exact builds you are using 
(Builds downloaded from here are taken into account: https://github.com/shadps4-emu/shadPS4/actions).
Is the Sound Pack still necessary?
Attach screenshots of the graphical errors.
Attach shad_log - "emulator folder"\user\log

This information will help narrow down the search for the causes of these problems.
The emulator is still at an early stage of development, so problems arise periodically, and their solutions may be postponed due to higher priorities, but information about them is welcome.

**Comment by ovojake** [comment] 2024-11-22 00:20
Alright so a couple things changed since last night. Yes the sound mod was still necessary, at least to play the 60fps patch. I've since downloaded the remaster project 0.7 mod, which again broke the sound unless I disabled the 60fps patch. So now I have the two mods. 

I tried recreating all 3 bugs on a new character. equipping clothing no longer crashes, but the other two bugs still happen. the white light in the clinic https://imgur.com/NUebbps. the vertex explosion also happens at random, reloading the game will fix or cause it to happen https://imgur.com/wb6ELWB

My first character still crashed when I try reequipping the garb and trousers (hat and gloves are fine). This doesn't happen on my new character though, so not really a big deal (for now) here's the log after the crash that occurs on my first character
[shad_log.txt](https://github.com/user-attachments/files/17853600/shad_log.txt)


Details:
Ryzen 5 5600, GTX 1080 8GB, 16GB RAM, Windows 11, shadps4 0.4.1 WIP main f9ae945. when I wrote the original post, I had the stable 0.4 release from your website.

**Comment by GHU7924** [comment] 2024-11-22 09:41
Mods can negatively affect the game, the authors of the emulator are not responsible for this.

But if I understood correctly, then you need mods Vertex Explosion Fix (disables face customization) and Bloodborne Object Flash Fix for Old Gpu's from NexusMods.

**Comment by Hermiten** [comment] 2024-12-02 19:32
Thanks you for this report
Everything is present here: https://github.com/shadps4-emu/shadPS4/issues/1641
I'm closing this one.

**Closed as completed by Hermiten** 2024-12-02 19:32 UTC
