### ISSUE TITLE
Launching Bloodborne while an xbox controller is on removes sound effects and music

### ISSUE THREAD

**Issue by DERDAR921** [shadps4-emu/shadPS4#1662] opened 2024-12-04 08:30 UTC
version v0.4.1

**Comment by Missake212** [comment] 2024-12-04 08:33
Most likely not the reason why you have no sound tbh, if you're on main 0.4.1 it's most likely related to the 60 fps patch, try relaunching the game without the 60fps patch and see if sound effects are back.

**Comment by DERDAR921** [comment] 2024-12-04 09:42
> Most likely not the reason why you have no sound tbh, if you're on main 0.4.1 it's most likely related to the 60 fps patch, try relaunching the game without the 60fps patch and see if sound effects are back.

its feels random cuz launching the game with 30fps patch fixed it with the controller on, then it was also fixed with 60fps patch. and then it didnt. but yeah, at least i know what to do if that happened again.

**Comment by Missake212** [comment] 2024-12-04 09:47
It's a known issue on the Discord with the 60 fps patch, it's caused by crashing or closing the game without quitting to the main menu with the 60 fps patch on, try this if you ever have your sound effects disappearing :
![image](https://github.com/user-attachments/assets/6df31482-1d13-440a-b900-ad4c81ee5c08)

**Closed as completed** 2024-12-05 11:32 UTC
