### ISSUE TITLE
[Feature Request] Support multiple game directories

### ISSUE THREAD

**Issue by Foul-Tarnished** [shadps4-emu/shadPS4#1304] opened 2024-10-09 00:17 UTC
Let us choose multiple folders where to look for games.

Why:
- Some users want to store some games on a HDD, while other on a SSD.
- Some users store games on a NAS, while keeping a few locally (useful for laptops, when you travel and only keep a few games when travelling, keeping your full library at home on your NAS)

**Comment by Hermiten** [comment] 2024-10-09 06:11
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/226

**Comment by Hermiten** [comment] 2024-10-09 06:12
You can see progress here https://github.com/shadps4-emu/shadPS4/pull/1308

**Closed by Hermiten** 2024-10-09 06:12 UTC
