### ISSUE TITLE
Unusual crash for bloodborne everytime I try to boot it with a new build

### ISSUE THREAD

**Issue by Jaswanth-Vardireddy** [shadps4-emu/shadPS4#694] opened 2024-08-31 17:22 UTC
![image](https://github.com/user-attachments/assets/130fcae5-9203-458b-abd4-3710d61a198d)
^This has never happened before on older builds so I'm confused if it's something I am able to fix. I was able to get to the character creator screen before but now the game just completely crashes with that error above after a short grey screen. Is there a way to fix this?

**Comment by MysteriousAeon** [comment] 2024-08-31 18:00
![image](https://github.com/user-attachments/assets/7d97f7f3-67c9-44f3-92cc-48a539f23a98)
Also having this with a 5800x3D and a 4070 Super.

**Comment by FragsAreUs** [comment] 2024-08-31 23:10
I found that after hitting new game or next when first creating a character to just start right away and don't allow the cutscene to play out

**Comment by Jaswanth-Vardireddy** [comment] 2024-08-31 23:17
> I found that after hitting new game or next when first creating a character to just start right away and don't allow the cutscene to play out

Thing is I can't even get into the game/main menu cuz it immediatly crashes when the game boots up.

**Comment by hgh32** [comment] 2024-09-01 00:36
What gpu do you use?
https://github.com/shadps4-emu/shadPS4/pull/575
According to my test, any version including this pr will not work
If you delete the gxshader.shaderbnd.dcx file in the game shader directory, you can enter the title menu

**Comment by Jaswanth-Vardireddy** [comment] 2024-09-01 00:48
> What gpu do you use? #575 According to my test, any version including this pr will not work If you delete the gxshader.shaderbnd.dcx file in the game shader directory, you can enter the title menu

Intel iris Xe. I haven't seen many people try with intel so idk if this is the expected outcome.

**Comment by Warzone848** [comment] 2024-09-01 09:54
![image](https://github.com/user-attachments/assets/9e3da83c-f5b7-40c8-8a79-fef26abe5280)
keeps crashing without error here at the particular screen, not sure how to fix!!

**Comment by MysteriousAeon** [comment] 2024-09-01 10:04
Figured it out. Y'all need the bb-hacks build. https://docs.google.com/document/u/0/d/17WixYgtwTdTeqL0NFKEqVrzCWu7Wr-x7/mobilebasic

**Comment by Warzone848** [comment] 2024-09-01 10:24
it crashes my game. once I see my character etc game freezes then crashes

**Comment by Hermiten** [comment] 2024-10-01 22:11
Intel Iris XE is GPU integrated and may not work for this emulator

**Comment by StevenMiller123** [comment] 2024-10-01 22:21
There is consideration going into properly supporting Intel ARC based graphics. Even if it's an iGPU, Iris Xe graphics are part of the ARC architecture, and so I think issues reported using Iris Xe graphics should be considered valid (Well, unless the issue is specifically from VRAM, but that isn't the case here).

**Comment by Hermiten** [comment] 2024-10-01 22:34
That right, it's why I let it open. 
I'm warning him, though, that it could take time

**Comment by Missake212** [comment] 2024-12-22 16:45
Can you guys test again on latest nightly? My Intel iGPU (Intel UHD Graphics 770) doesn't crash anymore and gets in game since #1683 got merged to main.

**Closed as completed** 2024-12-22 19:35 UTC
