### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by ironfarkus** [shadps4-emu/shadPS4#1841] opened 2024-12-21 21:57 UTC
Hello,

When following the instruction in https://github.com/shadps4-emu/shadPS4/blob/main/documents/building-windows.md, for Option 2 (the one that doesnt require Qt), at the `cmake --build build` step I get this error

FAILED: CMakeFiles/shadps4.dir/src/common/ntapi.cpp.obj
C:\msys64\mingw64\bin\clang++.exe -DBOOST_ASIO_STANDALONE -DENABLE_DISCORD_RPC -DGLSLANG_IS_SHARED_LIBRARY=1 -DIMGUI_USER_CONFIG=\"imgui/imgui_config.h\" -DNOMINMAX -DNTDDI_VERSION=0x0A000006 -DTRACY_ENABLE -DTRACY_NO_CALLSTACK -DTRACY_NO_CODE_TRANSFER -DTRACY_NO_CONTEXT_SWITCH -DTRACY_NO_CRASH_HANDLER -DTRACY_NO_FRAME_IMAGE -DTRACY_NO_SAMPLING -DTRACY_NO_SYSTEM_TRACING -DTRACY_ONLY_LOCALHOST -DTRACY_ON_DEMAND -DWIN32_LEAN_AND_MEAN -DWINVER=0x0A00 -DZYCORE_STATIC_BUILD -DZYDIS_STATIC_BUILD -D_WIN32_WINNT=0x0A00 -IC:/msys64/home/../shadPS4/src -IC:/msys64/home/../shadPS4 -IC:/msys64/home/../shadPS4/build/src/video_core/host_shaders/include -IC:/msys64/home/../shadPS4/build/src/imgui/renderer/generated_fonts -isystem C:/msys64/home/../shadPS4/externals/magic_enum/include -isystem C:/msys64/home/../shadPS4/externals/fmt/include -isystem C:/msys64/home/../shadPS4/externals/toml11/include -isystem C:/msys64/home/../shadPS4/externals/robin-map/include -isystem C:/msys64/home/../shadPS4/externals/xbyak -isystem C:/msys64/home/../shadPS4/externals/tracy/public -isystem C:/msys64/home/../shadPS4/externals/./renderdoc -isystem C:/msys64/home/../shadPS4/externals/dear_imgui -isystem C:/msys64/home/../shadPS4/externals/gcn/include -isystem C:/msys64/home/../shadPS4/externals/half/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/align/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/range/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/optional/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/utility/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/tuple/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost/libs/iterator/include -isystem C:/msys64/home/../shadPS4/externals/ext-boost -isystem C:/msys64/home/../shadPS4/externals/vma/include -isystem C:/msys64/home/../shadPS4/externals/LibAtrac9/C/src -isystem C:/msys64/home/../shadPS4/externals/sirit/src/../include -isystem C:/msys64/home/../shadPS4/externals/sirit/externals/SPIRV-Headers/include -isystem C:/msys64/home/../shadPS4/externals/vulkan-headers/include -isystem C:/msys64/home/../shadPS4/externals/xxhash -isystem C:/msys64/home/../shadPS4/externals/zydis/include -isystem C:/msys64/home/../shadPS4/build/externals/zydis -isystem C:/msys64/home/../shadPS4/externals/zydis/dependencies/zycore/include -isystem C:/msys64/home/../shadPS4/build/externals/zydis/zycore -isystem C:/msys64/home/../shadPS4/build/externals/sdl3/include-revision -isystem C:/msys64/home/../shadPS4/externals/sdl3/include -isystem C:/msys64/home/../shadPS4/externals/pugixml/src -isystem C:/msys64/home/../shadPS4/externals/stb -isystem C:/msys64/home/../shadPS4/build/externals/cryptopp -isystem C:/msys64/home/../shadPS4/externals/winpthreads/include -isystem C:/msys64/home/../shadPS4/externals/discord-rpc/include -O2 -march=native -O3 -DNDEBUG -std=gnu++23 -DHAVE_PTHREAD_MUTEX_TIMEDLOCK -Wno-error=unused-command-line-argument -MD -MT CMakeFiles/shadps4.dir/src/common/ntapi.cpp.obj -MF CMakeFiles\shadps4.dir\src\common\ntapi.cpp.obj.d -o CMakeFiles/shadps4.dir/src/common/ntapi.cpp.obj -c C:/msys64/home/../shadPS4/src/common/ntapi.cpp
In file included from C:/msys64/home/../shadPS4/src/common/ntapi.cpp:6:
C:/msys64/home/../shadPS4/src/common/ntapi.h:509:24: error: unexpected type name 'TEB': expected expression
  509 | static_assert(offsetof(TEB, DeallocationStack) ==
  	|                    	^
C:/msys64/home/../shadPS4/src/common/ntapi.h:509:29: error: use of undeclared identifier 'DeallocationStack'
  509 | static_assert(offsetof(TEB, DeallocationStack) ==
  	|                         	^
2 errors generated.
[573/789] Building CXX object CMakeFiles/shadps4.dir/src/common/config.cpp.obj
ninja: build stopped: subcommand failed.

I'm not sure what I am missing.

**Comment by ConfidentlyIncorrect** [comment] 2024-12-24 01:32
same issue as me, have not seen a fix around

**Comment by polybiusproxy** [comment] 2024-12-26 16:36
Marking as duplicate of https://github.com/shadps4-emu/shadPS4/issues/1900

**Closed as completed by polybiusproxy** 2024-12-26 16:36 UTC
