### ISSUE TITLE
The emulator crashes after choising game

### ISSUE THREAD

**Issue by PrimalSmite** [shadps4-emu/shadPS4#1134] opened 2024-09-28 19:08 UTC
The emulator crashes when you click on a game from the list. Sometimes you can select a game, but when you launch it, you get an error there. Running on the archlinux kernel 6.10.10-arch1-1 with NVIDIA GeForce RTX 2060 SUPER with nvidia-open-560.35.03-6 drivers

Logs:

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GLib-GObject-CRITICAL **: 23:01:37.199: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_element_link_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

(shadps4:15251): GStreamer-CRITICAL **: 23:01:37.199: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed
fish: Job 1, './Shadps4-qt.AppImage' terminated by signal SIGSEGV (Address boundary error)

**Comment by Hermiten** [comment] 2024-10-01 21:46
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/1157
Fixed by https://github.com/shadps4-emu/shadPS4/pull/1187

**Closed as completed** 2024-10-01 21:48 UTC
