### ISSUE TITLE
shadps4 crashes in windows when launching Bloodborne

### ISSUE THREAD

**Issue by dp27thelight** [shadps4-emu/shadPS4#821] opened 2024-09-06 22:28 UTC
[shad_log.txt](https://github.com/user-attachments/files/16913482/shad_log.txt)

![log](https://github.com/user-attachments/assets/672444f5-cf0c-40f2-abd4-f91080ddbff4)

i9 13980hx 
RTX 4090 Mobile 16GB Vram
32 GB ram

Ryzen 7945HX
RTX 4090 Mobile 16GB Vram
32 GB ram

Ryzen 5800h
6600m 8GB
16 GB ram

All systems crash when launching Bloodborne in windows, but they all boot Bloodborne in Linux.

sync is selected, I've seen people with similar issue's not aware what's going on. I don't have sys_modules, but that's not an issue in Linux. Windows updated, driver's updated and I've tried dozen of builds.

**Comment by arginineD3** [comment] 2024-09-07 02:19
i have the exact problom

**Comment by dp27thelight** [comment] 2024-09-07 02:51
Did you add sys_modules? I added sys_modules and the results were the same.

**Comment by dp27thelight** [comment] 2024-09-07 05:25
[Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

Missing the classic Visual C++ Redistributable sometimes I forget to install that on windows.

**Comment by rmueller83** [comment] 2024-09-07 09:33
Duplicate of #726

**Comment by Hermiten** [comment] 2024-10-01 16:36
closed because duplicate

**Closed as completed by Hermiten** 2024-10-01 16:36 UTC
