### ISSUE TITLE
When installing the pkg file, the emulator crashes 

### ISSUE THREAD

**Issue by yeitsu** [shadps4-emu/shadPS4#884] opened 2024-09-12 12:46 UTC
When installing the pkg file, the emulator crashes and only 11 mb of game is installed

**Comment by StevenMiller123** [comment] 2024-09-13 17:42
Please provide the hardware specs of the device you are using to test.

**Comment by rmueller83** [comment] 2024-09-13 18:48
Duplicate of #692

**Comment by yeitsu** [comment] 2024-09-14 09:43
1070 ti
xeon 2650 v2
16gb ddr3
windows 11

**Comment by Curseslowbeauty** [comment] 2024-09-14 12:55
running shadps4 as administrator solved this problem for me

**Comment by yeitsu** [comment] 2024-09-14 13:16
I've tried it already

**Comment by XPacL** [comment] 2024-09-16 13:35
Same issue

**Comment by Dhrazer** [comment] 2024-09-17 12:00
> 1070 ti xeon 2650 v2 16gb ddr3 windows 11
Correct me if I'm wrong but the V2 Xeons don't support AVX2 only V4 and up... Neither the installer nor the emulator itself functions without AVX2.
I swapped an i7 2600k to an R7 7700 and now it run...

**Comment by Dhrazer** [comment] 2024-09-17 12:01
> 1070 ti xeon 2650 v2 16gb ddr3 windows 11

Correct me if I'm wrong but the V2 Xeons don't support AVX2. Without it neither the installer nor the emulator works

**Closed as completed** 2024-09-20 02:27 UTC
