### ISSUE TITLE
[Aggregate Issue] Mapping cannot fit inside free region

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#825] opened 2024-09-07 04:20 UTC
Separated as aggregate.

Fat princess adventures - CUSA01660
```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0x200000
```

Diablo II Resurrected - CUSA28305

```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0x96800000
```

**Comment by gandalfthewhite19890404** [comment] 2024-09-07 04:47
Resident Evil 2 (2019) - CUSA09171
```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0xce000000
```

**Comment by StevenMiller123** [comment] 2024-09-16 20:46
@polybiusproxy Should we move the remaining crash logs from #601 here? All the remaining ones are the same type of error as this. It would make testing easier since we wont need to test on a month old build.

**Comment by Hermiten** [comment] 2024-10-01 15:54
@StevenMiller123 Can you confirm if the regression is still here ?

**Comment by StevenMiller123** [comment] 2024-10-04 12:18
Call of Duty®: Advanced Warfare v1.00 - CUSA00803
```
[Debug] <Critical> memory.cpp:operator():640: Assertion Failed!
Mapping cannot fit inside free region: size = 0x80000000
```
Crash™ Team Racing Nitro-Fueled v1.00 - CUSA13795
```
[Debug] <Critical> memory.cpp:operator():640: Assertion Failed!
Mapping cannot fit inside free region: size = 0x20000000
```

**Comment by Rokkag** [comment] 2024-10-17 04:35
Kai No Kieski v1.00 - CUSA49295
```
[Debug] <Critical> memory.cpp:operator():644: Assertion Failed!
Mapping cannot fit inside free region: size = 0x24000000
```

**Comment by Hermiten** [comment] 2024-12-01 14:12
CUSA32600 - ARMORED CORE™ VI FIRES OF RUBICON™  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/1263
```
[Debug] memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x1ad00000
```
CUSA10525 - Darkest Dungeon  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/930
```
[Debug] memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0xc0000
```
CUSA12474 - TOKYO GHOUL:re CALL to EXIST  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/785
```
[Debug] memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0x21810000
```
CUSA00634 - STAR WARS™ Battlefront™  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/768
```
[Debug] <Critical> memory.cpp:operator():544: Assertion Failed!
Mapping cannot fit inside free region
```
CUSA40994 - Amnesia: The Bunker  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/731
```
[Debug] memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0xa5e00000
```
CUSA13801 - Sekiro™: Shadows Die Twice  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/688
```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed! 
Mapping cannot fit inside free region: size = 0xc0000000
```
CUSA19264 - 妖怪学園Y ～ワイワイ学園生活～/Yokai Academy Y: Lively School Life  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/620
```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0x300000
```
CUSA18880 ELDEN RING™ Network Test Ver  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/597
```
[Debug] memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x4000000
```
CUSA28832 - 那由多之軌跡：改 (Nayuta no Kiseki KAI)  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/445
```
[Debug] memory.cpp:operator():415: Assertion Failed!
Mapping cannot fit inside free region
```
CUSA19640 - Persona 5 Strikers  https://github.com/shadps4-emu/shadps4-game-compatibility/issues/56
```
[Debug] <Critical> memory.cpp:operator():568: Assertion Failed!
Mapping cannot fit inside free region: size = 0xd2800000
```

**Comment by kvicken** [comment] 2024-12-08 01:39
CUSA28194 - SONIC FRONTIERS  shadps4-emu/shadps4-game-compatibility#388
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x52000000
```
CUSA32600 - ARMORED CORE™ VI FIRES OF RUBICON™ shadps4-emu/shadps4-game-compatibility#1263
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x1ad00000
```
CUSA18723 - ELDEN RING™ shadps4-emu/shadps4-game-compatibility#1332
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x20000000
```
CUSA11993 - Marvel's Spider-Man shadps4-emu/shadps4-game-compatibility#1353
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0x10000000
```
CUSA17776 - Marvel's Spider-Man: Miles Morales shadps4-emu/shadps4-game-compatibility#978
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0xdb00000
```
CUSA13801 - Sekiro™: Shadows Die Twice shadps4-emu/shadps4-game-compatibility#688
```
[Debug] <Critical> memory.cpp:operator():655: Assertion Failed!
Mapping cannot fit inside free region: size = 0xc0000000

**Comment by smiRaphi** [comment] 2024-12-12 00:23
CUSA04301 - Dreams™
```
[Debug] <Critical> memory.cpp:operator():663: Assertion Failed!
Mapping cannot fit inside free region: size = 0x4000000
```

**Comment by bigol83** [comment] 2024-12-18 11:14
CUSA15325 - Yakuza 3
```

[Debug] <Critical> memory.cpp:operator():663: Assertion Failed!
Mapping cannot fit inside free region: size = 0x9800000
```

[shad_log.txt](https://github.com/user-attachments/files/18180261/shad_log.txt)

**Comment by Hermiten** [comment] 2024-12-28 13:04
@gandalfthewhite19890404 , @StevenMiller123, @kvicken can we close it ?
This https://github.com/shadps4-emu/shadPS4/pull/1896 normally fix it

**Comment by StevenMiller123** [comment] 2024-12-28 14:28
@Hermiten I agree this should be closed. The main "regression" we were tracking is fixed, and most of the games listed here are confirmed to be fixed.

**Comment by Hermiten** [comment] 2024-12-28 14:30
Wonderful

**Closed as completed by Hermiten** 2024-12-28 14:30 UTC
Labels: contributor wanted
