### ISSUE TITLE
Game directory window appears every time

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#361] opened 2024-08-03 05:40 UTC
When you drag and drop eboot.bin to shadps4-qt executable, game directory choose window appears every time.

**Comment by Xphalnos** [comment] 2024-08-03 06:29
This is normal, you are using the build that contains an interface. You must use the SDL build

**Comment by yaya54840** [comment] 2024-08-03 06:44
hi guys
yes
In my case I created shortcuts
it's work but it's much easier for testing games

![Capture d'écran 2024-08-03 084014](https://github.com/user-attachments/assets/52ef9c91-7e9b-46b5-a4c5-73a3443ae47a)

**Comment by gandalfthewhite19890404** [comment] 2024-08-03 07:56
> This is normal, you are using the build that contains an interface. You must use the SDL build

I think it is not normal. If game directory was set in config it shouldn't be asked next time, and behaviour gonna be same as console app if eboot or elf was drag'n'dropped.

**Comment by DanielSvoboda** [comment] 2024-08-04 03:09
This is defined in this code, if opened through the interface it creates it in the executable location, however when executed via the command line or by dragging from the SDL, it creates the `user` folder in the eboot.bin directory.

https://github.com/shadps4-emu/shadPS4/blob/6d0a7631456486bf4fe5a13f2085111e7fdf6f5a/src/common/path_util.cpp#L59


`PORTABLE_DIR` is just the name of the folder that will be created `user` which is defined in "src/common/path_util.h"

**Comment by yaya54840** [comment] 2024-08-04 06:37
Hello
Ok Daniel I have roughly grasped the principle at my level. :)
Thank you for these explanations.
What Gandalf may mean: the Qt interface should not close when you close the window to stop the execution of the current game because each time you have to restart it.
But at the speed of your work it will evolve.

**Comment by gandalfthewhite19890404** [comment] 2024-08-04 10:25
> What Gandalf may mean: the Qt interface should not close when you close the window to stop the execution of the current game because each time you have to restart it.
> But at the speed of your work it will evolve.

I suggest this variant as option - when you drag'n'dropped eboot.bin to shadps4's exe emulation should start immediately.

**Comment by SamuelFontes** [comment] 2024-08-08 19:18
If a game was passed as command line argument, it should start automatically as this is the expected behaviour.
I've created a new pull request that solves this issue: https://github.com/shadps4-emu/shadPS4/pull/381

**Comment by SamuelFontes** [comment] 2024-08-08 21:09
> When you drag and drop eboot.bin to shadps4-qt executable, game directory choose window appears every time.

The pull request was merged, please confirm if this solves the issue.

**Comment by lzardy** [comment] 2024-08-08 21:11
> > When you drag and drop eboot.bin to shadps4-qt executable, game directory choose window appears every time.
> 
> The pull request was merged, please confirm if this solves the issue.

Yes, this correctly solves the issue as of ab56665.

**Closed as completed** 2024-08-08 21:12 UTC
