### ISSUE TITLE
Some Issues when playing Bloodborne with ShadPS4

### ISSUE THREAD

**Issue by Rheckar** [shadps4-emu/shadPS4#940] opened 2024-09-16 07:27 UTC
Hello, thanks for all your work first of all. As a pc lover and someone who just doesn't want to bother with learning how to play with a console your work means a lot. I have made Bloodborne work somehow up to the point of running almost seamlessly with a couple of problems. The first one that you notice is the lightning issue but personally I don't mind it all that much. The second and the major one that affects gameplay the most is probably the crash when getting hit or hitting problem. Another crash is when you use an item (? not sure but it's the animation that happens when you press up arrow key.)

[https://imgur.com/P3xtpg7]
[https://imgur.com/QepZWgz]
[https://imgur.com/qpGKWJA]
[https://imgur.com/x1p9aW5]

Not sure if these help or you're all aware of these issues but hope it helps. Tested with the WIP versions shadps4-win64-qt-2024-09-15-b09b28c, shadps4-win64-qt-2024-09-15-a90b22e, shadps4-win64-qt-2024-09-16-f44e0d8.
Also are there any keyboard bindings guide? Couldn't find it on the website.

**Comment by StevenMiller123** [comment] 2024-09-16 23:21
None of those images you've linked are showing up, though most of the issues you describe are known issues. Keyboard bindings are on the Github readme, just scroll down in the code tab and you'll see them.

**Comment by Rheckar** [comment] 2024-09-17 08:15
Thank you, the images were just logs of the crash but if the issues are known then they're not needed I guess.

**Comment by Mikiri7** [comment] 2024-09-18 05:50
https://www.youtube.com/watch?v=Xi1q49N0sKE
For keyboar and mouse

**Comment by Hermiten** [comment] 2024-10-01 17:15
duplicate of a lot of issue. Can you please use the search toolbar before posting an issue.
Thanks you anyway for the report.

**Closed as completed by Hermiten** 2024-10-01 17:15 UTC
