### ISSUE TITLE
Disabling keyboard input

### ISSUE THREAD

**Issue by Draiza** [shadps4-emu/shadPS4#1877] opened 2024-12-25 13:59 UTC
Any way to disable or remap keyboard input in game? I tried to make virtual controller input with Virtual Controller but native ShadPS4 keyboard inputs that I can't change have higher priority so it's impossible to play via mouse and keyboard even with side programs. I saw controller icon in emulator and thought that was what I searched but it does nothing on click.

**Comment by Missake212** [comment] 2024-12-25 14:00
There's currently an open PR that aims to add KMB remapping. You can follow the progression here https://github.com/shadps4-emu/shadPS4/pull/1797

**Comment by Hermiten** [comment] 2024-12-28 18:41
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/298

**Closed as completed by Hermiten** 2024-12-28 18:41 UTC
