### ISSUE TITLE
getting error on new update

### ISSUE THREAD

**Issue by Crasthiff** [shadps4-emu/shadPS4#1225] opened 2024-10-03 21:06 UTC
![image](https://github.com/user-attachments/assets/c692b485-97bc-42ac-afcb-929d4df48973)

any help? kinda new here, screen goes black and crash

**Comment by Hermiten** [comment] 2024-10-04 08:53
I'm closing it. Please use issue search box or come on discord to ask for help like this. 
Or if it's a regression, we need more information (since when, which OS version, etc...)

**Closed as completed by Hermiten** 2024-10-04 08:53 UTC
