### ISSUE TITLE
Patches screen are empty

### ISSUE THREAD

**Issue by zoxon** [shadps4-emu/shadPS4#1394] opened 2024-10-16 15:35 UTC
The download buttons work, and the patch files downloaded without any problems

Unable to install any patches because the UI is empty

Tested on latest stable (v0.3.0) version and on latest nightly build v0.3.1 (25de4d6) 

OS: Windows 11 Pro 23H2 22631.4317

![2024-10-16_21-30-04](https://github.com/user-attachments/assets/a83a564d-481a-4f2b-a0f6-348f6e32daa4)

**Comment by StevenMiller123** [comment] 2024-10-16 15:40
This isn't an actual issue. There are no patches for Bloodborne v1.00, You need to dump the update file for the game in order to run any patches.

**Comment by Hermiten** [comment] 2024-10-16 16:53
Maybe it can be a good idea to put something, like a text to say "There is no patches found for this games or this version"
?

**Comment by Hermiten** [comment] 2024-10-16 16:56
Maybe @DanielSvoboda ?

**Comment by DanielSvoboda** [comment] 2024-10-16 18:24
@StevenMiller123 That's right, 1.0 doesn't have a patch, only for 1.9.
The patch is downloaded for all games, not just the one currently on the screen, so the message is for all games and doesn't search for the current serial and version.
I think this message is pretty self-explanatory, don't you think? In my opinion, all you need to do is pay attention when reading it.
![image](https://github.com/user-attachments/assets/16207861-ea03-4f39-9ab9-23a70e64daf5)

**Comment by Hermiten** [comment] 2024-10-16 18:44
> @StevenMiller123 That's right, 1.0 doesn't have a patch, only for 1.9. The patch is downloaded for all games, not just the one currently on the screen, so the message is for all games and doesn't search for the current serial and version. I think this message is pretty self-explanatory, don't you think? In my opinion, all you need to do is pay attention when reading it. ![image](https://private-user-images.githubusercontent.com/28203966/377181902-16207861-ea03-4f39-9ab9-23a70e64daf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDQ1MDIsIm5iZiI6MTcyOTEwNDIwMiwicGF0aCI6Ii8yODIwMzk2Ni8zNzcxODE5MDItMTYyMDc4NjEtZWEwMy00ZjM5LTlhYjktMjNhNzBlNjRkYWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE4NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWMxMDQ3NTVmZWY5MDZhNmJmY2U0Y2YyNzQwMjVkYzNkMDg0NjZkMTIyMjMzMGM3NDVjMGMxZDE0Mjk0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zZjPcNX3n0qYyuJ33LYbfMzv5YnvDAK8lJas7qFhkRY)

That true. But you know people, so it can maybe help to avoid issue like this 🤣

**Comment by ElBread3** [comment] 2024-10-16 18:54
> That true. But you know people, so it can maybe help to avoid issue like this 🤣

Could probably have a text in the middle of the list saying "No patches found for this version :(" when there isn't any found

**Comment by DanielSvoboda** [comment] 2024-10-16 18:56
This message is already in the emulator.
What I could do is check if the patches being downloaded are compatible with the version and serial number opened in the window and make a personalized warning, but this download only happens once, because it downloads all the patches for all the available games at once, so I don't think it makes sense to change this.
I think it's fine like this, all that's missing is the attention of the person reading it 🧐

**Comment by par274** [comment] 2024-10-16 20:29
This is a problem caused by a PR called "Seperate Update". Fixed #1397 

It hasn't been included in the main yet.

**Comment by DanielSvoboda** [comment] 2024-10-16 22:53
> This is a problem caused by a PR called "Seperate Update". Fixed #1397
> 
> It hasn't been included in the main yet.

There is no patch for this game because there is no patch for the version it is using, 1.0. There is only a patch for version 1.9.
And it was mentioned that version 0.3.0 and PR1392 were used.

Does PR1397 cause the emulator to not recognize the installed version?

**Comment by ElBread3** [comment] 2024-10-16 23:46
> cause the emulator to not recognize the installed version?

It's is a side effect of when I was implementing the separate updates (#1026, #1387) it wasn't fully reading the update as I didn't realize the separate update folder contained eboots that needed to be used, and so it uses the old version from the base folder. This is fixed with #1397 and should now fully load updates and work correctly. That's what par274's saying

**Comment by zoxon** [comment] 2024-10-17 03:13
Thank you. I forget to install patch file.

It would be nice if we had a message to install the patch file after installing the base game, if it's in the same folder.

**Comment by DanielSvoboda** [comment] 2024-10-17 16:23
yes, I'll try to do that, and maybe make a screen to manage them all, showing which patches are installed and which version of the game is installed.

**Closed as completed** 2024-10-17 17:25 UTC
