### ISSUE TITLE
Bloodborne graphic bug

### ISSUE THREAD

**Issue by LouderLimix** [shadps4-emu/shadPS4#976] opened 2024-09-18 18:30 UTC
![image](https://github.com/user-attachments/assets/52ee8454-97cc-4193-8f39-bdf15657e509)

As you can see, sometimes (kinda frequently) my character looks just like this. Version of emulator is 0.2.1 WIP and the cmd shows this:

![image](https://github.com/user-attachments/assets/6dff197c-ecde-4072-926a-52941408b4b3)

I had Bloodborne FPS Boost mod, the sound pack mod, no players light mod and the 60fps patch on. Even If I change some of this stuff I just mentioned, the problem persists and I havent found a solution yet. Any help, please?

**Comment by imximxi** [comment] 2024-09-19 11:34
Try "in-game" quitting to main menu and then reload your save, does this fix it occasionally, possibly not everytime. 

Also OS, GPU  + Driver Version ?

**Comment by demonslayer228** [comment] 2024-09-19 11:51
How do you play with sfx? Or you deleted it?

**Comment by imximxi** [comment] 2024-09-19 11:52
Completely from factory

**Comment by LouderLimix** [comment] 2024-09-19 14:32
> Try "in-game" quitting to main menu and then reload your save, does this fix it occasionally, possibly not everytime.
> 
> Also OS, GPU + Driver Version ?

Yes, it fixes it sometimes, but im doing a no-hit run and suddenly having this in the middle of a fight or section is kinda complicated. OS is Windows 11 Home, GPU is NVIDIA GeForce RTX 4060 TI, drivers version 552.12 and 32GB RAM

**Comment by Hermiten** [comment] 2024-10-01 21:17
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/968

**Closed as completed by Hermiten** 2024-10-01 21:17 UTC

**Comment by LouderLimix** [comment] 2024-10-02 01:09
this is not closed, nobody answered my question, tf

**Comment by lucajazz84** [comment] 2024-11-17 14:52
Same to me, completely random, and oftne appears after I died .. My rig is 4080 and 5800x3d with 32gb ram @3800mz c16
