### ISSUE TITLE
Can't start the game.

### ISSUE THREAD

**Issue by Xenon02** [shadps4-emu/shadPS4#1092] opened 2024-09-26 23:51 UTC
I've installed the base game + the 1.09 patch but everytime I start the game I get the black screen, some errors and then it closes both bloodborn and shad4PS. 

This is what I get, dunno what to do to be honest.

```[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved VVgqI3B2bfk as _FNan (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 2sWzhYqFH4E as _Stdout (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved H8AprKeZtNg as _Stderr (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:259: Not Resolved module_stop
[Core.Linker] <Info> linker.cpp:operator():240: function not patched! module_stop
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved H2e8t5ScQGc as __cxa_finalize (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:259: Not Resolved module_start
[Core.Linker] <Info> linker.cpp:operator():240: function not patched! module_start
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved sqWytnhYdEg as _ZNSt8ios_base4InitC1Ev (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved tsvEmnenz48 as __cxa_atexit (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved -Bl9-SZ2noc as _ZNSt6_WinitC1Ev (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved tQIo+GIPklo as _ZSt14_Xlength_errorPKc (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved z+P+xCnWLBk as _ZdlPv (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved PDX01ziUz+4 as _ZSt13_Syserror_mapi (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved +P6FRGH4LfA as memmove (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved fJnpuVVBbKk as _Znwm (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved eT2UsmTewbU as _ZSt11_Xbad_allocv (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved ozMAr28BwSY as _ZSt14_Xout_of_rangePKc (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved ZE6RNL+eLbk as tanf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved L1SBTkC+Cvw as abort (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved cpCOXWMgha0 as rand (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved iz2shAGFIxc as hypotf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved hcuQgD53UxM as printf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved YQ0navp+YIc as puts (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved AEJdIVZTEmo as qsort (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved m5wN+SwZOR4 as putchar (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved DDHG1a6+3q0 as roundf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved hdm0YfMa7TQ as _Znam (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved MLWl90SFWNE as _ZdaPv (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved mnufPlYbnN0 as _FDtest (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved zXCi78bYrEI as _Log (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved kn0yiYeExgA as ldexpf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved EH-x713A99c as atan2f (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 1D0H2KNjshE as powf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved jjjRS7l1MPM as _FLog (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved Lyx2DzUL7Lc as fmaxf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved RWqyr1OKuw4 as logbf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 9fs1btfLoUs as scalbnf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved ZtjspkJQ+vw as _FSin (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved -3pU5y1utmI as _FExp (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved tIhsqj0qsFE as free (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved b-xTWRgI1qw as _Dtest (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved QI-x0SL8jhw as acosf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved VPbJwTCgME0 as srand (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved MUjC4lbHrK4 as fflush (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved 9LCjpWyQ5Zc as pow (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved fffwELXNVFA as fprintf (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved rtV7-jWC6Yg as log (lib: libSceLibcInternal, mod: libSceLibcInternal)
[Kernel.Vmm] <Info> memory_management.cpp:sceKernelMapNamedFlexibleMemory:208: addr = 0x880000000, len = 0x4000, prot = 0x3, flags = 0x0
[Core.Linker] <Info> module.cpp:Start:71: Module started : libc
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibcHeap00000009100BB788, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_Atexit, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_Locale, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_Malloc, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_Stream, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_Debug, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_FileStdin, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_FileStdout, result=0
[Kernel.Pthread] <Info> thread_management.cpp:scePthreadMutexInit:452: name=SceLibc_FileStderr, result=0
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceFace
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceFios2
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceHand
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceHeadTracker
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x94fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x94fffc074
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceS3DConversion
[Core.Linker] <Info> module.cpp:Start:71: Module started : libSceSmart
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x97003b3c3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x97003b3dc
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x97003b3eb
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x970036b83
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x970036b9c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x970036bab
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x9700237d3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x9700237ec
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x9700237fb
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x96fffed93
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffedac
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x96fffedbb
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x96fffd223
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffd23c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x96fffd24b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt8ios_base4InitC1Ev (nid: sqWytnhYdEg) called, returning zero to 0x96fffc963
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc97c
[Core] <Error> stubs.cpp:CommonStub:42: Stub: _ZNSt6_WinitC1Ev (nid: -Bl9-SZ2noc) called, returning zero to 0x96fffc98b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: __cxa_atexit (nid: tsvEmnenz48) called, returning zero to 0x96fffc074```

**Comment by StevenMiller123** [comment] 2024-09-26 23:59
This issue seems to occur when people install encrypted patches, I'd recommend testing without the patch applied.

**Comment by Xenon02** [comment] 2024-09-27 11:49
> This issue seems to occur when people install encrypted patches, I'd recommend testing without the patch applied.

Nah even going back to 1.0 it still can't launch, it refuses to even start or show anything like Fromsoft logo, it is just black screen and then closes the Bloodborn and the ShadPS4

**Comment by StevenMiller123** [comment] 2024-09-29 14:36
Then, assuming your base game was a pkg install, your Bloodborne v1.00 dump was likely encrypted. Make sure to dump your games through the proper homebrew methods, not through ftp.

**Comment by PrimalSmite** [comment] 2024-09-29 18:41
I have the same issue with same logs. If you will find good pgk file pls notify me

**Comment by scarletcxz** [comment] 2024-10-03 17:16
did you manage to solve this problem?

**Comment by polybiusproxy** [comment] 2024-10-03 17:22
Closing as the issue is a broken dump (might be corrupted or most likely encrypted as said before).

**Closed as not planned by polybiusproxy** 2024-10-03 17:22 UTC
