### ISSUE TITLE
[CUSA13413][Version 01.06] Black screen when running Darkwood

### ISSUE THREAD

**Issue by BuyMyMojo** [shadps4-emu/shadPS4#565] opened 2024-08-24 17:53 UTC
When trying to launch Darkwood it will throw a ton of errors into console until it hit's a point of slowly printing out the same error over and over again:

```
[Lib.GnmDriver] <Info> gnmdriver.cpp:sceGnmSubmitDone:2139: called
[Tty] <Info> libkernel.cpp:ps4__write:210: Forcing submitDone to avoid TRC R4089 breach
```

Full log + debugdump folder: [log.zip](https://github.com/user-attachments/files/16737523/log.zip)

Tested with commit [9e4fc17](https://github.com/shadps4-emu/shadPS4/commit/9e4fc17e6c2e18b4e4c7707115378b31a1ee4210)

**Comment by BuyMyMojo** [comment] 2024-08-24 18:30
I forgot to copy of the sys modules again with the new version, here is the updated log in case you need it but it has the exact same issue: [log.zip](https://github.com/user-attachments/files/16737628/log.zip)

**Comment by Hermiten** [comment] 2024-10-01 14:55
Thanks you, it's a common error, we can follow this issue or maybe closing it now that we know what the problem is

**Closed as completed** 2024-10-01 15:06 UTC
